## YAML Template.
---
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login
      MYSQL_USER: root
      MYSQL_PASSWORD: dhivya@28
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  bloodbank-app:
    build:
      context: .
    container_name: bloodbank-app
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  mysql_data:

