/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodBank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author dhivy
 */
public class AddReceiver extends javax.swing.JFrame {

    /**
     * Creates new form AddReceiver
     */
    public AddReceiver() {
        initComponents();
        setSize(707, 510);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Add Receiver");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 30, 130, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Receiver Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 110, 100, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 170, 60, 21);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Age");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 290, 50, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Phone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 360, 70, 21);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 110, 70, 30);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 110, 150, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 170, 150, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 290, 150, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 350, 150, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(530, 110, 150, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 170, 70, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Blood Type");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 230, 100, 21);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(530, 170, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(530, 220, 150, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 420, 80, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 420, 80, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Username");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 230, 90, 21);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 230, 150, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Password");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(410, 290, 90, 21);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(530, 280, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBank/home.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 710, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int id;
            try {
                id= Integer.parseInt(jTextField1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Donor ID ");
                return;
            }
        
            String Name=jTextField2.getText();
             String Names="^[a-zA-Z']+$";
             if (!Name.matches(Names)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Name");
            return; 
    }
         
        String username=jTextField7.getText();
         String usernameregex="^[a-zA-Z0-9]+(?: [a-zA-Z0-9]+)*$";
            Pattern pattern2=Pattern.compile(usernameregex);
            Matcher matcher2=pattern2.matcher(username);
            if(!matcher2.matches()){
                    JOptionPane.showMessageDialog(this,"Invalid username","Error",JOptionPane.ERROR_MESSAGE);
                    return;
            }
        int Age;
         try {
            Age = Integer.parseInt(jTextField3.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Age");
            return;
        }
         
         
        String phoneStr = jTextField4.getText();
        if (phoneStr.length() != 10 || !phoneStr.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid 10-digit phone number");
        return; 
    }
    String Phone_No = phoneStr;
    String Email=jTextField5.getText();
    String emailPattern = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b";
    if (!Email.matches(emailPattern)) {
        JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
        return; 
    }
    String Address=jTextField6.getText();
    if(Address.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter a valid Address");
    }
    String Blood_Type=jComboBox1.getSelectedItem().toString();
    if ( Name.isEmpty() || Phone_No.isEmpty()||Email.isEmpty()||Address.isEmpty()||Blood_Type.isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
        }
    String password = new String(jPasswordField1.getPassword()); 
    if(!isValidPassword(password)){
                JOptionPane.showMessageDialog(this,"Invalid password.Password must contain atleast one uppercase,one lowercase,one digit and one special character.","Error",JOptionPane.ERROR_MESSAGE);
                return;
    }
    String usertype="Receiver";

        try {
        Connection con = DbConnection.connect();
        String query = "INSERT INTO receiverlogin(id,name, username, age, Phone_No, email, address,Blood_Type,password,usertype) VALUES (?,?, ?, ?, ?, ?,?,?,?,?)";
        PreparedStatement st = con.prepareStatement(query);
        st.setInt(1, id);
        st.setString(2, Name);
        st.setString(3, username);
        st.setInt(4, Age);
        st.setString(5, Phone_No );
        st.setString(6, Email);
        st.setString(7, Address);
        st.setString(8,Blood_Type);
        st.setString(9,password);
        st.setString(10,usertype);
       
        int rowsAffected = st.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Receiver added successfully");
            clearTextFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to Receiver");
        }
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error. " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Receiver().setVisible(true);
        dispose();   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clearTextFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
   // jTextField7.setText("");   // TODO add your handling code here:
    }                                                                           
    private boolean isValidPassword(String password){
        //password must contain one upparcase,one lowercase,one digit,one special characters
        String passwordregex="^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$^&+=!])(?=\\S+$).{8,}$";
        Pattern pattern4=Pattern.compile(passwordregex);
        Matcher matcher4=pattern4.matcher(password);
        return matcher4.matches();
    }
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReceiver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
