/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodBank;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import static java.nio.file.Files.lines;
import static java.nio.file.Files.lines;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author dhivy
 */
public class OrderBlood extends javax.swing.JFrame {

    /**
     * Creates new form OrderBlood
     */
    public OrderBlood() {
        initComponents();
        setSize(660, 480);
        setLocationRelativeTo(null);
        setResizable(false);
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentShown(java.awt.event.ComponentEvent evt) {
            formComponentShown(evt);  // ✅ This triggers the method
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Blood");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 80, 50, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 140, 50, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Blood Center");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 200, 110, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Blood Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 260, 100, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Unit");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 310, 50, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 80, 180, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(450, 140, 180, 30);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(450, 200, 180, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(450, 260, 180, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(450, 310, 180, 30);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 380, 90, 30);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 380, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBank/order blood.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 650, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText(); 
        String city=jComboBox1.getSelectedItem().toString();
        String blood_center=jComboBox2.getSelectedItem().toString();
        String blood_Type=jComboBox3.getSelectedItem().toString();
        int unit=Integer.parseInt(jTextField2.getText());
        try{
            unit=Integer.parseInt(jTextField2.getText());
        }
        catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this,"Invalid input for unit.Please enter a valid number","Error",JOptionPane.ERROR_MESSAGE);
        }
//        double unitPrice=Double.parseDouble(jTextField3.getText());
        int unitPrice=200;
        int totalPrice=unit*unitPrice;
        try{            
                Connection con=DbConnection.connect();
                String receiverName="select id from receiverlogin where name=? and usertype='Receiver' ";
                int id=-1;
                try(PreparedStatement pt=con.prepareStatement(receiverName)){
                    pt.setString(1,name);
                    ResultSet set=pt.executeQuery();
                    if(set.next()){
                        id=set.getInt("id");
                    }
                }
                if(id!=-1){
                    String query="insert into orderBlood(id,city,blood_center,blood_Type,unit,lastUpdated) values(?,?,?,?,?,CURRENT_TIMESTAMP)";
                    try(PreparedStatement st=con.prepareStatement(query)){
                        st.setInt(1, id);
                        st.setString(2, city);
                        st.setString(3, blood_center);
                        st.setString(4, blood_Type);
                        st.setInt(5, unit);
                        st.executeUpdate(); 
                    }
                    update(city,blood_center,blood_Type,unit);
                    clearTextFields();
                    JOptionPane.showMessageDialog(this,"Receiver Ordered blood Successfully\n Name: "+name+"\nCity: "+city+"\nBlood Center: "+blood_center+"\nUnit: "+unit+"\nTotal Price: "+totalPrice);
                    String bill=generateBill(id,name,city,blood_center,blood_Type,unit,totalPrice);
                    JOptionPane.showMessageDialog(this,bill,"Order Bill",JOptionPane.INFORMATION_MESSAGE);
                    printBill(bill);        
                }
                else{
                    if(unit<=0){
                        JOptionPane.showMessageDialog(this,"Blood not available","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Receiver Not Found","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Error while adding data","Error",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String city=jComboBox1.getSelectedItem().toString();
        System.out.println("--"+city+"--");  
        jComboBox2.removeAllItems();
        try{
            Connection con=DbConnection.connect();
            String query="select blood_center from stock where city='"+city+"';";
            PreparedStatement st=con.prepareStatement(query);
            ResultSet rs = st.executeQuery();
            while(rs.next()){
                String name=rs.getString("blood_center");               
                jComboBox2.addItem(name);
            }
            con.close();
        }
        catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new BloodBankAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
                                        
    private void update(String city,String blood_center,String blood_Type,int unit){
        try{
            Connection con=DbConnection.connect();
            String updatequery="update stock set `"+blood_Type+"` = `" + blood_Type+"` - ? where blood_center=? and city=? ";
            System.out.println("Unit: "+unit);
            System.out.println("Blood center: "+blood_center);
            System.out.println("City: "+city);
            try(PreparedStatement st1=con.prepareStatement(updatequery)){
                st1.setInt(1, unit);
                st1.setString(2, blood_center);
                st1.setString(3, city);
                st1.executeUpdate();
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Error while updating data","Error",JOptionPane.ERROR_MESSAGE);
        } 
    
    }
    
    private void printBill(String bill){
        PrinterJob job=PrinterJob.getPrinterJob();//print job
        job.setPrintable(new Printable(){//set printable object for this print job
           public int print(Graphics g,PageFormat pf,int page) throws PrinterException{//calling printing system
                if(page>0){//handling multiple pages
                    return NO_SUCH_PAGE;//1st first page get printed and after that subsequent will get printed
                }
                Graphics2D gd=(Graphics2D) g;//img,chart
                gd.translate(pf.getImageableX(),pf.getImageableY());
                String[] lines=bill.split("\n");//content
                Font font=new Font("Times New Roman",Font.PLAIN,16);
                g.setFont(font);
                FontMetrics metrics=g.getFontMetrics(font);//calculate line height
                int height=metrics.getHeight();
                int y=100;//initalise the y-axis
                for(String line:lines){
                    g.drawString(line, 100, y);//draw each line at given posi
                    y+=height;//update y-cor for nextline
                }
                return PAGE_EXISTS;
           }
        });
        if(job.printDialog()){
            try{
                job.print();
            }
            catch(PrinterException e){
            JOptionPane.showMessageDialog(this,"Error while printing","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }
    
    private void clearTextFields(){
           jTextField1.setText("");
           jTextField2.setText("");
    }                                       
    private String generateBill(int id,String name,String city,String blood_center,String blood_Type,int unit,int totalPrice){
                    StringBuilder bill=new StringBuilder();
                    bill.append("---------------------Blood Order Bill-------------------------\n");
                    bill.append("Id: ").append(id).append("\n");
                    bill.append("Name: ").append(name).append("\n");
                    bill.append("City: ").append(city).append("\n");
                    bill.append("Blood Center: ").append(blood_center).append("\n");
                    bill.append("Blood Type: ").append(blood_Type).append("\n");
                    bill.append("Unit: ").append(unit).append("\n");
                    bill.append("TotalPrice: ").append(totalPrice).append("\n");
                    bill.append("-------------------------------"+java.time.LocalDateTime.now()+"------------------------------");
//                    JOptionPane.showMessageDialog(this,bill.toString(),"Order Bill",JOptionPane.INFORMATION_MESSAGE);
                    return bill.toString();
    }                                        

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
        // TODO add your handling code here:
            jComboBox1.removeAllItems();
            try{
                Connection con=DbConnection.connect();
                String query="select distinct city from stock;";
                PreparedStatement st=con.prepareStatement(query);
                ResultSet rs = st.executeQuery();
                while(rs.next()){
                    String name=rs.getString("city");
                    jComboBox1.addItem(name);
                }
                con.close();

            }
            catch (SQLException e){
                System.out.println(e);
            }
        
    }                                   
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderBlood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderBlood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
